# Generated by Django 5.2.6 on 2025-09-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sepatu', 'Sepatu'), ('jersey', 'Jersey'), ('bola', 'Bola'), ('tas', 'Tas'), ('kaoskaki', 'Kaos Kaki'), ('atribut', 'Atribut')], default='update', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
